[0000]
encoding="utf-8"
commit_hash = "f5993d463b4988d85fe81ebb58dff3b3bb175d14"
regexes = ["[\\sR"]
should_parse = [false]

[0001]
commit_hash = "f5993d463b4988d85fe81ebb58dff3b3bb175d14"
encoding = "binascii"
regexes = ["5c_26_0a_c3"]
should_parse = [false]
