pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'make port'
      }
    }
    stage('Run Simple Tests') {
      steps {
        sh 'make -C build/port'
      }
    }
    stage('Run OOM Tests') {
      steps {
        sh 'make -C build/port testoom'
      }
    }
  }
}
